### ISSUE TITLE
Suddenly stopped working on 07/02/2021

### ISSUE THREAD

**Issue by ningji** [bradlucas/get-yahoo-quotes#6]
Downloading dltr to dltr.csv
Traceback (most recent call last):
  File "get-yahoo-quotes.py", line 91, in <module>
    download_quotes(symbol)
  File "get-yahoo-quotes.py", line 78, in download_quotes
    cookie, crumb = get_cookie_crumb(symbol)
  File "get-yahoo-quotes.py", line 56, in get_cookie_crumb
    cookie, lines = get_page_data(symbol)
  File "get-yahoo-quotes.py", line 46, in get_page_data
    cookie = get_cookie_value(r)
  File "get-yahoo-quotes.py", line 40, in get_cookie_value
    return {'B': r.cookies['B']}
  File "/home/ningji/.local/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/ningji/.local/lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='B', domain=None, path=None"

i believe 6/30 it was still working, any suggestions ? thx very much !

**Comment by alancurtis2** [comment]
I found that the page still worked with firefox, so added the firefox User-Agent string to all the get requests with the headers argument to the request calls. Now works for me. I am not using this package, but a similar one. Ymmv

**Comment by bradlucas** [comment]
ningji, I've updated the project adding the user agent as alancurtis2 suggested. It should work fine now. Let me know if it doesn't or if there still and issue.

Thanks,
Brad

**Comment by ningji** [comment]
The new script is working. (BTW think i created issue for the wrong one, i was using the python version before. But i'm happy this script works as well.) Thanks very much to both of you !

**Comment by bradlucas** [comment]
You are welcome. Thanks for letting me know. Earlier I checked and updated the Python version with the same user agent fix. So you should be set with that one as well.
